email:
  sender: aamtayag@gmail.com
  password: your_app_password_here
  smtp_server: smtp.gmail.com
  smtp_port: 587

recipients:
  - user01@example.com
  - user02@example.com
  - user03@example.com
  - user04@example.com
  - user05@example.com
  - user06@example.com
  - user07@example.com
  - user08@example.com
  - user09@example.com
  - user10@example.com
  - user11@example.com
  - user12@example.com
